[2018-11-15T11:16:43.408] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\TOOLSWEB\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:564:33)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-11-15T11:16:43.411] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-15T11:21:11.674] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T11:21:15.678] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T11:22:50.607] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T11:36:52.557] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T12:45:41.338] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T12:47:07.093] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T12:47:45.936] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T12:48:41.380] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T12:49:19.493] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T12:49:22.594] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T12:49:44.740] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T12:51:05.868] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T12:51:27.527] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T12:51:53.235] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, unlink 'D:\work\TOOLSWEB\toolsWeb\uploaded\undefined'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\uploaded\\undefined' }
[2018-11-15T15:22:52.516] [ERROR] dateFileLog - { Error: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_LOCK_WAIT_TIMEOUT',
  errno: 1205,
  sqlState: 'HY000',
  index: 0,
  sql: 'delete  from OA_staffs where DBID = 143' }
[2018-11-15T15:22:52.522] [ERROR] dateFileLog - Error: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-15T15:25:01.516] [ERROR] dateFileLog - { Error: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_LOCK_WAIT_TIMEOUT',
  errno: 1205,
  sqlState: 'HY000',
  index: 0,
  sql: 'delete  from OA_staffs where DBID = 142' }
[2018-11-15T15:25:01.523] [ERROR] dateFileLog - Error: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-15T15:26:48.814] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'staff_ID' in 'field list'
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0,
  sql: 'insert into OA_staffs (staff_ID,dept,deptClass,deptGroup,staffName,sex,deptFee,postName,postLevel,edu,company,birthday,entryDate,inUnion,Phone,major,school,degree,certificates,gradTime) values (\'111\',\'软体部\',\'主机课\',\'主机组\',\'1111\',\'男\',\'\',\'\',\'员工级\',\'本科\',\'弘讯科技\',\'\',\'\',\'是\',\'\',\'\',\'\',\'\',\'\',\'\')' }
[2018-11-15T15:26:48.820] [ERROR] dateFileLog - Error: ER_BAD_FIELD_ERROR: Unknown column 'staff_ID' in 'field list'
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-15T15:31:53.645] [ERROR] dateFileLog - { Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'birthday' at row 1
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '22007',
  index: 0,
  sql: 'insert into OA_staffs (photo,dept,deptClass,deptGroup,staffName,sex,shortPhone,postName,postLevel,edu,company,birthday,entryDate,runNum,Phone,major,school,degree,certificates,gradTime) values (\'\',\'软体部\',\'主机课\',\'主机组\',\'11111\',\'男\',\'\',\'1111\',\'员工级\',\'本科\',\'弘讯科技\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'\')' }
[2018-11-15T15:31:53.651] [ERROR] dateFileLog - Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'birthday' at row 1
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
