[2018-09-19T07:58:19.723] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-19T07:58:19.731] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T07:58:23.882] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-19T07:58:23.884] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T07:58:42.687] [ERROR] dateFileLog - { Error: ER_DUP_ENTRY: Duplicate entry '1-171' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  index: 0,
  sql:
   ' insert into RolesAuthority (RoleOID,ProcessOID,ActionOID,Value) select 1,171,ActionOID,1 from ProcessesActions' }
[2018-09-19T07:58:42.688] [ERROR] dateFileLog - Error: ER_DUP_ENTRY: Duplicate entry '1-171' for key 'PRIMARY'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T07:58:53.825] [ERROR] dateFileLog - { Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:460:23)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  index: 0,
  sql:
   ' insert into RolesAuthority (RoleOID,ProcessOID,ActionOID,Value) values(1,170,2,1)' }
[2018-09-19T07:58:53.827] [ERROR] dateFileLog - Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T08:01:23.927] [ERROR] dateFileLog - { Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  index: 0,
  sql:
   ' insert into RolesAuthority (RoleOID,ProcessOID,ActionOID,Value) values(1,170,21,1)' }
[2018-09-19T08:01:23.929] [ERROR] dateFileLog - Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T08:03:17.037] [ERROR] dateFileLog - { Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  index: 0,
  sql:
   ' insert into RolesAuthority (RoleOID,ProcessOID,ActionOID,Value) values(1,170,2,1)' }
[2018-09-19T08:03:17.040] [ERROR] dateFileLog - Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T08:07:02.898] [ERROR] dateFileLog - { Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  index: 0,
  sql:
   ' insert into RolesAuthority (RoleOID,ProcessOID,ActionOID,Value) values(1,170,2,1)' }
[2018-09-19T08:07:02.900] [ERROR] dateFileLog - Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T08:07:08.301] [ERROR] dateFileLog - { Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  index: 0,
  sql:
   ' insert into RolesAuthority (RoleOID,ProcessOID,ActionOID,Value) select 1,170,ActionOID,1 from ProcessesActions' }
[2018-09-19T08:07:08.307] [ERROR] dateFileLog - Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T08:09:45.656] [ERROR] dateFileLog - { Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  index: 0,
  sql:
   ' insert into RolesAuthority (RoleOID,ProcessOID,ActionOID,Value) select 1,170,ActionOID,1 from ProcessesActions' }
[2018-09-19T08:09:45.658] [ERROR] dateFileLog - Error: ER_DUP_ENTRY: Duplicate entry '1-170' for key 'PRIMARY'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T08:09:51.411] [ERROR] dateFileLog - { Error: ER_DUP_ENTRY: Duplicate entry '1-171' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  index: 0,
  sql:
   ' insert into RolesAuthority (RoleOID,ProcessOID,ActionOID,Value) values(1,171,2,1)' }
[2018-09-19T08:09:51.413] [ERROR] dateFileLog - Error: ER_DUP_ENTRY: Duplicate entry '1-171' for key 'PRIMARY'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T08:11:12.479] [ERROR] dateFileLog - { Error: ER_DUP_ENTRY: Duplicate entry '1-171' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  index: 0,
  sql:
   ' insert into RolesAuthority (RoleOID,ProcessOID,ActionOID,Value) values(1,171,2,1)' }
[2018-09-19T08:11:12.481] [ERROR] dateFileLog - Error: ER_DUP_ENTRY: Duplicate entry '1-171' for key 'PRIMARY'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T08:35:09.320] [ERROR] dateFileLog - Error: Not found 'mes' in Projects.
    at D:\work\Source\yujiang.Foil.Node.BizServer\biz\org\processAuthority.js:127:7
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query._callback (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
[2018-09-19T08:39:26.923] [ERROR] dateFileLog - TypeError: Cannot read property 'headers' of undefined
    at WebSocketServer.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjPusher.ws.js:58:27)
    at WebSocketServer.emit (events.js:182:13)
    at WebSocketServer.EventEmitter.emit (domain.js:442:20)
    at D:\work\Source\node_modules\ws\lib\WebSocketServer.js:91:14
    at completeHybiUpgrade2 (D:\work\Source\node_modules\ws\lib\WebSocketServer.js:284:5)
    at completeHybiUpgrade1 (D:\work\Source\node_modules\ws\lib\WebSocketServer.js:309:13)
    at WebSocketServer.handleHybiUpgrade (D:\work\Source\node_modules\ws\lib\WebSocketServer.js:337:3)
    at WebSocketServer.handleUpgrade (D:\work\Source\node_modules\ws\lib\WebSocketServer.js:173:26)
    at Server.WebSocketServer._onServerUpgrade (D:\work\Source\node_modules\ws\lib\WebSocketServer.js:89:12)
    at Server.emit (events.js:187:15)
[2018-09-19T08:47:37.448] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-19T08:47:37.450] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T09:13:37.725] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsWeb.erpcatogory' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM erpcatogory ' }
[2018-09-19T09:13:37.729] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsWeb.erpcatogory' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T09:15:13.875] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsWeb.erpcatogory' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM erpcatogory ' }
[2018-09-19T09:15:13.877] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsWeb.erpcatogory' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T09:16:33.411] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsWeb.erpcatogory' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM erpcatogory ' }
[2018-09-19T09:16:33.413] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsWeb.erpcatogory' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-19T09:40:36.685] [ERROR] dateFileLog - { ReferenceError: D:\work\Source\toolsWeb\web\app\bear\BearSub.{v}.ejs:11
    9| 
    10| //<%- blocks.BearAdd%>
 >> 11| 
    12| <% block('BearAdd',partial("./BearAdd.ejs")) -%> 
    13| <%-body%>
    14| 

body is not defined
    at eval (eval at exports.compile (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:533)
    at eval (eval at exports.compile (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:1462)
    at D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
    at Object.exports.renderFile (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:318:20)
    at View.module.exports [as engine] (D:\work\Source\node_modules\ejs-locals\index.js:85:7)
    at View.render (D:\work\Source\node_modules\express\lib\view.js:126:8)
    at tryRender (D:\work\Source\node_modules\express\lib\application.js:639:10)
    at Function.render (D:\work\Source\node_modules\express\lib\application.js:591:3)
    at ServerResponse.render (D:\work\Source\node_modules\express\lib\response.js:961:7)
  path: 'D:\\work\\Source\\toolsWeb\\web\\app\\bear\\BearSub.{v}.ejs' }
[2018-09-19T09:40:59.983] [ERROR] dateFileLog - { ReferenceError: D:\work\Source\toolsWeb\web\app\bear\BearSub.{v}.ejs:11
    9| 
    10| <%- blocks.BearAdd%>
 >> 11| 
    12| <% block('BearAdd',partial("./BearAdd.ejs")) -%> 
    13| <%-body%>
    14| 

body is not defined
    at eval (eval at exports.compile (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:531)
    at eval (eval at exports.compile (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:1460)
    at D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
    at Object.exports.renderFile (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:318:20)
    at View.module.exports [as engine] (D:\work\Source\node_modules\ejs-locals\index.js:85:7)
    at View.render (D:\work\Source\node_modules\express\lib\view.js:126:8)
    at tryRender (D:\work\Source\node_modules\express\lib\application.js:639:10)
    at Function.render (D:\work\Source\node_modules\express\lib\application.js:591:3)
    at ServerResponse.render (D:\work\Source\node_modules\express\lib\response.js:961:7)
  path: 'D:\\work\\Source\\toolsWeb\\web\\app\\bear\\BearSub.{v}.ejs' }
[2018-09-19T09:42:40.952] [ERROR] dateFileLog - { ReferenceError: D:\work\Source\toolsWeb\web\app\bear\BearSub.{v}.ejs:12
    10| <%- blocks.BearAdd%>
    11| 
 >> 12| 
    13| <%-body%>
    14| <% block('BearAdd',partial("./BearAdd.ejs")) -%> 
    15| 

body is not defined
    at eval (eval at exports.compile (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:457)
    at eval (eval at exports.compile (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:1460)
    at D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
    at Object.exports.renderFile (D:\work\Source\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:318:20)
    at View.module.exports [as engine] (D:\work\Source\node_modules\ejs-locals\index.js:85:7)
    at View.render (D:\work\Source\node_modules\express\lib\view.js:126:8)
    at tryRender (D:\work\Source\node_modules\express\lib\application.js:639:10)
    at Function.render (D:\work\Source\node_modules\express\lib\application.js:591:3)
    at ServerResponse.render (D:\work\Source\node_modules\express\lib\response.js:961:7)
  path: 'D:\\work\\Source\\toolsWeb\\web\\app\\bear\\BearSub.{v}.ejs' }
