[2018-12-04T08:38:28.201] [ERROR] dateFileLog - { ReferenceError: D:\work\TOOLSWEB\toolsWeb\web\app\PM\0ordersAdmin.{v}.ejs:140
    138| <tbody>
    139|   <tr>
 >> 140|      <td>订单总数</td>
    141|      <td><%=dataRows%></td>
    142|   </tr>
    143|   <tr>

dataRows is not defined
    at eval (eval at exports.compile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:4278)
    at eval (eval at exports.compile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:11955)
    at D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
    at Object.exports.renderFile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:318:20)
    at View.module.exports [as engine] (D:\work\TOOLSWEB\node_modules\ejs-locals\index.js:85:7)
    at View.render (D:\work\TOOLSWEB\node_modules\express\lib\view.js:126:8)
    at tryRender (D:\work\TOOLSWEB\node_modules\express\lib\application.js:639:10)
    at Function.render (D:\work\TOOLSWEB\node_modules\express\lib\application.js:591:3)
    at ServerResponse.render (D:\work\TOOLSWEB\node_modules\express\lib\response.js:961:7)
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\web\\app\\PM\\0ordersAdmin.{v}.ejs' }
[2018-12-04T08:39:38.506] [ERROR] dateFileLog - { ReferenceError: D:\work\TOOLSWEB\toolsWeb\web\app\PM\0ordersAdmin.{v}.ejs:140
    138| <tbody>
    139|   <tr>
 >> 140|      <td>订单总数</td>
    141|      <td><%=dataRows%></td>
    142|   </tr>
    143|   <tr>

dataRows is not defined
    at eval (eval at exports.compile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:4278)
    at eval (eval at exports.compile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:11951)
    at D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
    at Object.exports.renderFile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:318:20)
    at View.module.exports [as engine] (D:\work\TOOLSWEB\node_modules\ejs-locals\index.js:85:7)
    at View.render (D:\work\TOOLSWEB\node_modules\express\lib\view.js:126:8)
    at tryRender (D:\work\TOOLSWEB\node_modules\express\lib\application.js:639:10)
    at Function.render (D:\work\TOOLSWEB\node_modules\express\lib\application.js:591:3)
    at ServerResponse.render (D:\work\TOOLSWEB\node_modules\express\lib\response.js:961:7)
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\web\\app\\PM\\0ordersAdmin.{v}.ejs' }
[2018-12-04T08:39:39.534] [ERROR] dateFileLog - { ReferenceError: D:\work\TOOLSWEB\toolsWeb\web\app\PM\0ordersAdmin.{v}.ejs:140
    138| <tbody>
    139|   <tr>
 >> 140|      <td>订单总数</td>
    141|      <td><%=dataRows%></td>
    142|   </tr>
    143|   <tr>

dataRows is not defined
    at eval (eval at exports.compile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:4278)
    at eval (eval at exports.compile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:11951)
    at D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
    at Object.exports.renderFile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:318:20)
    at View.module.exports [as engine] (D:\work\TOOLSWEB\node_modules\ejs-locals\index.js:85:7)
    at View.render (D:\work\TOOLSWEB\node_modules\express\lib\view.js:126:8)
    at tryRender (D:\work\TOOLSWEB\node_modules\express\lib\application.js:639:10)
    at Function.render (D:\work\TOOLSWEB\node_modules\express\lib\application.js:591:3)
    at ServerResponse.render (D:\work\TOOLSWEB\node_modules\express\lib\response.js:961:7)
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\web\\app\\PM\\0ordersAdmin.{v}.ejs' }
[2018-12-04T14:22:06.913] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'PKValue' in 'field list'
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing [as _callback] (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at Ping.Sequence.end (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Ping.Sequence.OkPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:105:8)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0,
  sql: 'insert into erpdb (PKValue) values(?)' }
[2018-12-04T17:51:14.353] [ERROR] dateFileLog - Error: TypeError: nodemailer.createTestAccount is not a function<br> &nbsp; &nbsp;at Object.&lt;anonymous&gt; (D:\work\TOOLSWEB\toolsWeb\biz\PM\sendMail.{post}.{m}.js:6:12)<br> &nbsp; &nbsp;at Module._compile (module.js:653:30)<br> &nbsp; &nbsp;at Object.Module._extensions..js (module.js:664:10)<br> &nbsp; &nbsp;at Module.load (module.js:566:32)<br> &nbsp; &nbsp;at tryModuleLoad (module.js:506:12)<br> &nbsp; &nbsp;at Function.Module._load (module.js:498:3)<br> &nbsp; &nbsp;at Module.require (module.js:597:17)<br> &nbsp; &nbsp;at require (internal/module.js:11:18)<br> &nbsp; &nbsp;at buildData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:161:21)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:129:5

    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-12-04T17:54:24.938] [ERROR] dateFileLog - Error: Error: Cannot find module &#39;nodemailer&#39;<br> &nbsp; &nbsp;at Function.Module._resolveFilename (module.js:548:15)<br> &nbsp; &nbsp;at Function.Module._load (module.js:475:25)<br> &nbsp; &nbsp;at Module.require (module.js:597:17)<br> &nbsp; &nbsp;at require (internal/module.js:11:18)<br> &nbsp; &nbsp;at Object.&lt;anonymous&gt; (D:\work\TOOLSWEB\toolsWeb\biz\PM\sendMail.{post}.{m}.js:2:20)<br> &nbsp; &nbsp;at Module._compile (module.js:653:30)<br> &nbsp; &nbsp;at Object.Module._extensions..js (module.js:664:10)<br> &nbsp; &nbsp;at Module.load (module.js:566:32)<br> &nbsp; &nbsp;at tryModuleLoad (module.js:506:12)<br> &nbsp; &nbsp;at Function.Module._load (module.js:498:3)

    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-12-04T18:09:01.432] [ERROR] dateFileLog - Error: TypeError: nodemailer.createTestAccount is not a function<br> &nbsp; &nbsp;at Object.&lt;anonymous&gt; (D:\work\TOOLSWEB\toolsWeb\biz\PM\sendMail.{post}.{m}.js:6:12)<br> &nbsp; &nbsp;at Module._compile (module.js:653:30)<br> &nbsp; &nbsp;at Object.Module._extensions..js (module.js:664:10)<br> &nbsp; &nbsp;at Module.load (module.js:566:32)<br> &nbsp; &nbsp;at tryModuleLoad (module.js:506:12)<br> &nbsp; &nbsp;at Function.Module._load (module.js:498:3)<br> &nbsp; &nbsp;at Module.require (module.js:597:17)<br> &nbsp; &nbsp;at require (internal/module.js:11:18)<br> &nbsp; &nbsp;at buildData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:161:21)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:129:5

    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-12-04T18:46:28.603] [ERROR] dateFileLog - Error: D:\work\TOOLSWEB\toolsWeb\biz\PM\sendMail.{post}.{m}.js:34<br> &nbsp; &nbsp; &nbsp; &nbsp;html: &#39;&lt;table class=&quot;table&quot; id=&quot;reportTable&quot;&gt;<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<br><br>SyntaxError: Invalid or unexpected token<br> &nbsp; &nbsp;at createScript (vm.js:80:10)<br> &nbsp; &nbsp;at Object.runInThisContext (vm.js:139:10)<br> &nbsp; &nbsp;at Module._compile (module.js:617:28)<br> &nbsp; &nbsp;at Object.Module._extensions..js (module.js:664:10)<br> &nbsp; &nbsp;at Module.load (module.js:566:32)<br> &nbsp; &nbsp;at tryModuleLoad (module.js:506:12)<br> &nbsp; &nbsp;at Function.Module._load (module.js:498:3)<br> &nbsp; &nbsp;at Module.require (module.js:597:17)<br> &nbsp; &nbsp;at require (internal/module.js:11:18)<br> &nbsp; &nbsp;at buildData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:161:21)

    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-12-04T18:47:31.019] [ERROR] dateFileLog - Error: D:\work\TOOLSWEB\toolsWeb\biz\PM\sendMail.{post}.{m}.js:34<br> &nbsp; &nbsp; &nbsp; &nbsp;html: &#39;<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^<br><br>SyntaxError: Invalid or unexpected token<br> &nbsp; &nbsp;at createScript (vm.js:80:10)<br> &nbsp; &nbsp;at Object.runInThisContext (vm.js:139:10)<br> &nbsp; &nbsp;at Module._compile (module.js:617:28)<br> &nbsp; &nbsp;at Object.Module._extensions..js (module.js:664:10)<br> &nbsp; &nbsp;at Module.load (module.js:566:32)<br> &nbsp; &nbsp;at tryModuleLoad (module.js:506:12)<br> &nbsp; &nbsp;at Function.Module._load (module.js:498:3)<br> &nbsp; &nbsp;at Module.require (module.js:597:17)<br> &nbsp; &nbsp;at require (internal/module.js:11:18)<br> &nbsp; &nbsp;at buildData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:161:21)

    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
