[2019-05-07T08:07:24.675] [ERROR] dateFileLog - { TypeError: D:\work\TOOLSWEB\toolsWeb\web\app\PM\billsTrack.{v}.ejs:449
    447| //页面加载函数---------------
    448| $(document).ready( function () {
 >> 449| 	
    450|     var sessionName="<%-locals.session.yjUser.Name%>";
    451| 	console.log("sessionName:"+sessionName);
    452| 	

Cannot read property 'Name' of undefined
    at eval (eval at exports.compile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:11447)
    at eval (eval at exports.compile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:15766)
    at D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
    at Object.exports.renderFile (D:\work\TOOLSWEB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:318:20)
    at View.module.exports [as engine] (D:\work\TOOLSWEB\node_modules\ejs-locals\index.js:85:7)
    at View.render (D:\work\TOOLSWEB\node_modules\express\lib\view.js:126:8)
    at tryRender (D:\work\TOOLSWEB\node_modules\express\lib\application.js:639:10)
    at Function.render (D:\work\TOOLSWEB\node_modules\express\lib\application.js:591:3)
    at ServerResponse.render (D:\work\TOOLSWEB\node_modules\express\lib\response.js:961:7)
  path: 'D:\\work\\TOOLSWEB\\toolsWeb\\web\\app\\PM\\billsTrack.{v}.ejs' }
[2019-05-07T08:28:55.088] [ERROR] dateFileLog - Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (D:\work\TOOLSWEB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\work\TOOLSWEB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\work\TOOLSWEB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\work\TOOLSWEB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:113:13)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:170:8)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
[2019-05-07T13:57:31.193] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:38:35.598] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:38:36.200] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:39:26.241] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:39:36.253] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:39:36.882] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:40:27.886] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:05.886] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:09.142] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:14.729] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:15.565] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:15.893] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:19.875] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:31.516] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:41.915] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:53.065] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:53.747] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:53.978] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:42:59.518] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:43:06.461] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:43:12.280] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:43:17.948] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:43:41.658] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:47:35.442] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:50:42.981] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:50:43.802] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:50:46.514] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:50:49.384] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:50:51.538] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:50:52.201] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:50:53.009] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:50:53.627] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:50:54.732] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:50:54.833] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:50:55.845] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:14.174] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:14.576] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:14.664] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:16.091] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:16.211] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:16.892] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:17.944] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:18.652] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:18.756] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:27.544] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:28.909] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:29.020] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:29.792] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:30.370] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:30.478] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:31.637] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:31.736] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:32.412] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:32.524] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:33.633] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:33.737] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:51:34.436] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:55:23.778] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:55:24.416] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:55:25.791] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:55:27.380] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T15:55:28.654] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:03:34.604] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:03:35.648] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:03:35.754] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:04:35.660] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:04:36.343] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:04:37.171] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:04:37.289] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:10:53.685] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:12:35.027] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:12:37.437] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:12:37.985] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:12:46.264] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:13:16.190] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:13:22.124] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:16:37.713] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:16:37.861] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:17:07.578] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:17:10.083] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:17:13.553] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:17:15.872] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:17:16.905] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:17:20.532] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:17:21.843] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:32.345] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:39.180] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:39.272] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:39.278] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:39.286] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:41.027] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:41.039] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:49.356] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:50.146] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:53.823] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:54.590] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:54.842] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:57.220] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:18:57.323] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:19:00.468] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:19:02.150] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:19:03.360] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:19:04.135] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:19:04.503] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:20:52.005] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T16:21:50.092] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:26:53.250] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:26:55.586] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:26:55.665] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:26:56.109] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:26:56.214] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:26:57.806] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:26:57.883] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:05.823] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:05.911] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:18.912] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:20.147] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:20.229] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:21.796] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:22.456] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:22.544] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:23.102] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:23.707] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:23.775] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:24.274] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:29.570] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:30.991] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:31.063] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:31.720] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:32.659] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:32.741] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:33.287] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:33.367] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:33.956] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:34.037] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:34.655] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:35.892] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:35.981] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:36.631] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:36.696] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:37.282] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:37.364] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:38.775] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:27:38.854] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:29:15.733] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:29:15.736] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:29:15.738] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:29:18.340] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:29:18.543] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:29:21.409] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:29:21.517] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:29:22.313] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:29:24.241] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:29:26.230] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:29:58.800] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:30:00.990] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:30:02.756] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:30:02.868] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:30:04.181] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:30:04.935] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:30:08.637] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:30:10.199] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:30:10.286] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:30:12.854] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:39:53.405] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:39:54.904] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:39:57.248] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:39:57.713] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:39:58.311] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:39:58.745] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:39:58.846] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:39:59.077] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:39:59.164] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:39:59.551] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:39:59.661] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:00.945] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:01.317] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:01.421] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:01.951] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:02.241] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:02.604] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:03.185] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:03.691] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:04.136] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:27.578] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:28.780] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:28.897] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:29.619] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:29.713] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:30.203] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:30.296] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:30.691] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:30.785] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:31.195] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:31.520] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:31.606] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:31.914] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:32.006] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:32.208] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:32.323] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:32.499] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:32.583] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:32.801] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:32.913] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:33.478] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:33.948] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:34.039] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:34.799] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:34.887] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:40:37.062] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:29.286] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:29.300] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:30.909] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:31.025] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:31.791] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:31.876] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:32.461] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:32.568] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:33.141] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:33.984] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:34.079] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:34.697] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:34.803] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:35.383] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:35.486] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:36.345] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:41:36.445] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:28.625] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:29.214] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:29.786] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:29.876] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:30.489] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:30.607] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:31.939] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:32.532] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:32.620] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:33.222] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:33.759] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:35.042] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:37.033] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:53.496] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:56.197] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:42:59.505] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:45:58.264] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:46:00.605] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:31.760] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:31.859] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:33.487] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:33.713] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:35.625] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:36.085] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:36.182] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:36.464] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:36.567] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:37.408] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:37.509] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:38.591] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:38.705] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:39.466] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:39.559] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:39.970] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:40.224] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:40.324] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:40.785] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:40.900] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:41.140] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:41.584] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:41.680] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:41.840] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:41.961] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:42.091] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:42.195] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:42.796] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-05-07T17:53:42.900] [ERROR] dateFileLog - Error: connect EADDRINUSE 127.0.0.1:2019
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:781:12)
    at ClientRequest.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:736:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
