[2018-11-06T08:23:36.324] [ERROR] dateFileLog - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''PM_customer'' at line 1
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0,
  sql: 'SELECT * FROM ? ' }
[2018-11-06T08:23:36.330] [ERROR] dateFileLog - Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''PM_customer'' at line 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T08:27:27.515] [ERROR] dateFileLog - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''PM_customer'' at line 1
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0,
  sql: 'SELECT * FROM ? ' }
[2018-11-06T08:27:27.519] [ERROR] dateFileLog - Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''PM_customer'' at line 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T08:29:33.468] [ERROR] dateFileLog - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROMPM_customer' at line 1
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0,
  sql: 'SELECT * FROMPM_customer' }
[2018-11-06T08:29:33.471] [ERROR] dateFileLog - Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROMPM_customer' at line 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T08:39:02.629] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM undefined' }
[2018-11-06T08:39:02.631] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T08:40:29.641] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM undefined' }
[2018-11-06T08:40:29.657] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T08:45:15.561] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM undefined' }
[2018-11-06T08:45:15.564] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T08:45:38.394] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM undefined' }
[2018-11-06T08:45:38.395] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T08:48:00.156] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM undefined' }
[2018-11-06T08:48:00.168] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T08:48:33.074] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM undefined' }
[2018-11-06T08:48:33.075] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T08:50:10.415] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM undefined' }
[2018-11-06T08:50:10.418] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T08:51:03.985] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM undefined' }
[2018-11-06T08:51:03.986] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsweb.undefined' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T10:16:56.706] [ERROR] dateFileLog - Error: Not found this user by userAID HMIUSer.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:106:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:564:33)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-11-06T10:16:56.709] [ERROR] dateFileLog - Error: Not found this user by userAID HMIUSer.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T13:48:36.541] [ERROR] dateFileLog - Error: SyntaxError: Unexpected identifier<br> &nbsp; &nbsp;at module.exports (D:\work\Source\toolsWeb\biz\PM\addDBData.{post}.{m}.js:6:33)<br> &nbsp; &nbsp;at buildData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\Source\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\Source\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\work\Source\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\work\Source\node_modules\express\lib\router\route.js:112:3)

    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T14:03:37.804] [ERROR] dateFileLog - Error: D:\work\Source\toolsWeb\biz\PM\addDBData.{post}.{m}.js:14<br> &nbsp; &nbsp;		console.log(j)；//显示属性的名称<br> &nbsp; &nbsp;		 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^<br><br>SyntaxError: Invalid or unexpected token<br> &nbsp; &nbsp;at createScript (vm.js:80:10)<br> &nbsp; &nbsp;at Object.runInThisContext (vm.js:139:10)<br> &nbsp; &nbsp;at Module._compile (module.js:617:28)<br> &nbsp; &nbsp;at Object.Module._extensions..js (module.js:664:10)<br> &nbsp; &nbsp;at Module.load (module.js:566:32)<br> &nbsp; &nbsp;at tryModuleLoad (module.js:506:12)<br> &nbsp; &nbsp;at Function.Module._load (module.js:498:3)<br> &nbsp; &nbsp;at Module.require (module.js:597:17)<br> &nbsp; &nbsp;at require (internal/module.js:11:18)<br> &nbsp; &nbsp;at buildData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:161:21)

    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T14:04:28.427] [ERROR] dateFileLog - Error: D:\work\Source\toolsWeb\biz\PM\addDBData.{post}.{m}.js:16<br> &nbsp; &nbsp;		console.log(j)；//显示属性的名称<br> &nbsp; &nbsp;		 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^<br><br>SyntaxError: Invalid or unexpected token<br> &nbsp; &nbsp;at createScript (vm.js:80:10)<br> &nbsp; &nbsp;at Object.runInThisContext (vm.js:139:10)<br> &nbsp; &nbsp;at Module._compile (module.js:617:28)<br> &nbsp; &nbsp;at Object.Module._extensions..js (module.js:664:10)<br> &nbsp; &nbsp;at Module.load (module.js:566:32)<br> &nbsp; &nbsp;at tryModuleLoad (module.js:506:12)<br> &nbsp; &nbsp;at Function.Module._load (module.js:498:3)<br> &nbsp; &nbsp;at Module.require (module.js:597:17)<br> &nbsp; &nbsp;at require (internal/module.js:11:18)<br> &nbsp; &nbsp;at buildData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:161:21)

    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T14:34:29.189] [ERROR] dateFileLog - Error: TypeError: tableTitle.Substring is not a function<br> &nbsp; &nbsp;at module.exports (D:\work\Source\toolsWeb\biz\PM\addDBData.{post}.{m}.js:21:27)<br> &nbsp; &nbsp;at buildData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\Source\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\Source\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\work\Source\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\work\Source\node_modules\express\lib\router\route.js:112:3)

    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T14:48:15.306] [ERROR] dateFileLog - Error: TypeError: tableTitle.TrimEnd is not a function<br> &nbsp; &nbsp;at module.exports (D:\work\Source\toolsWeb\biz\PM\addDBData.{post}.{m}.js:21:27)<br> &nbsp; &nbsp;at buildData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\Source\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\Source\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\work\Source\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\work\Source\node_modules\express\lib\router\route.js:112:3)

    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T14:49:16.822] [ERROR] dateFileLog - Error: TypeError: tableTitle.trimend is not a function<br> &nbsp; &nbsp;at module.exports (D:\work\Source\toolsWeb\biz\PM\addDBData.{post}.{m}.js:21:27)<br> &nbsp; &nbsp;at buildData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\Source\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\Source\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\work\Source\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\work\Source\node_modules\express\lib\router\route.js:112:3)

    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T14:49:45.102] [ERROR] dateFileLog - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') values (11,111,)' at line 1
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0,
  sql: 'insert into PM_customer (cust_FID,cust_Name,) values (11,111,)' }
[2018-11-06T14:49:45.109] [ERROR] dateFileLog - Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') values (11,111,)' at line 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-06T15:14:31.070] [ERROR] dateFileLog - { Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at D:\work\Source\yujiang.Foil.Node\src\yjApp.js:218:14
    at D:\work\Source\node_modules\async\lib\async.js:610:21
    at D:\work\Source\node_modules\async\lib\async.js:249:17
    at iterate (D:\work\Source\node_modules\async\lib\async.js:149:13)
    at async.eachSeries (D:\work\Source\node_modules\async\lib\async.js:165:9)
    at _asyncMap (D:\work\Source\node_modules\async\lib\async.js:248:13)
    at Object.mapSeries (D:\work\Source\node_modules\async\lib\async.js:231:23)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000 }
[2018-11-06T15:25:53.117] [ERROR] dateFileLog - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0,
  sql: 'insert into PM_customer (cust_FID,cust_Name) values (,)' }
[2018-11-06T15:25:53.123] [ERROR] dateFileLog - Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at args.(anonymous function) (D:\Program Files\nodejs\node_gobal\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
