[2018-09-17T09:36:11.232] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, scandir 'D:\work\Source\toolsWeb\web\system\release\data'
    at Object.fs.readdirSync (fs.js:904:18)
    at scanOne (D:\work\Source\yujiang.Foil.Node\src\yjDirectory.js:41:19)
    at Object.scanFiles (D:\work\Source\yujiang.Foil.Node\src\yjDirectory.js:68:10)
    at Object.<anonymous> (D:\work\Source\yujiang.Foil.Node.WebServer\app\system\release\readNewestVersion.{autorun}.js:13:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'D:\\work\\Source\\toolsWeb\\web\\system\\release\\data' }
[2018-09-17T13:35:03.088] [ERROR] dateFileLog - { Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Handshake.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Handshake.js:101:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at Protocol.handshake (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at PoolConnection.connect (D:\work\Source\node_modules\mysql\lib\Connection.js:109:18)
    at Pool.getConnection (D:\work\Source\node_modules\mysql\lib\Pool.js:45:23)
    at getConnection (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:81:12)
    at Object.exec (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:378:7)
    at Object.getOrgs (D:\work\Source\yujiang.Foil.Node.BizServer\biz\org\processAuthority\processAuthority.db.mysql.js:6:15)
    at buildOrgs (D:\work\Source\yujiang.Foil.Node.BizServer\biz\org\processAuthority.js:69:5)
    at fn (D:\work\Source\node_modules\async\lib\async.js:641:34)
    at Immediate.<anonymous> (D:\work\Source\node_modules\async\lib\async.js:557:34)
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  fatal: true }
[2018-09-17T13:36:15.410] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0,
  sql:
   ' select UserOID,Password,Name,UserAID,OrgOID ,AccessTypes from Users where UserAID=?' }
[2018-09-17T13:36:15.415] [ERROR] dateFileLog - Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:36:35.379] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0,
  sql:
   ' select UserOID,Password,Name,UserAID,OrgOID ,AccessTypes from Users where UserAID=?' }
[2018-09-17T13:36:35.382] [ERROR] dateFileLog - Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:36:38.428] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0,
  sql:
   ' select UserOID,Password,Name,UserAID,OrgOID ,AccessTypes from Users where UserAID=?' }
[2018-09-17T13:36:38.430] [ERROR] dateFileLog - Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:38:12.672] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0,
  sql:
   ' select UserOID,Password,Name,UserAID,OrgOID ,AccessTypes from Users where UserAID=?' }
[2018-09-17T13:38:12.674] [ERROR] dateFileLog - Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:38:27.633] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0,
  sql:
   ' select UserOID,Password,Name,UserAID,OrgOID ,AccessTypes from Users where UserAID=?' }
[2018-09-17T13:38:27.635] [ERROR] dateFileLog - Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:38:48.288] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:390:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:381:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:396:14)
    at Ping.runBound [as _callback] (domain.js:409:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0,
  sql:
   ' select UserOID,Password,Name,UserAID,OrgOID ,AccessTypes from Users where UserAID=?' }
[2018-09-17T13:38:48.289] [ERROR] dateFileLog - Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessTypes' in 'field list'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:43:06.307] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T13:43:06.315] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:49:10.583] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T13:49:10.585] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:55:10.591] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T13:55:10.593] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:57:41.155] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T13:57:41.158] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:57:47.202] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T13:57:47.203] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:57:51.944] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T13:57:51.946] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T13:57:53.342] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T13:57:53.344] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:02:07.044] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:02:07.046] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:02:09.284] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:02:09.285] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:02:09.406] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:02:09.408] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:02:12.047] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:02:12.049] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:02:12.227] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:02:12.228] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:02:12.435] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:02:12.437] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:05:42.090] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:05:42.096] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:09:03.103] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:119:17)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:09:03.106] [ERROR] dateFileLog - Error: Has no authority on this platform 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:20:37.944] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:20:37.946] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:20:47.572] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:20:47.573] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:20:55.460] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:20:55.462] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:21:29.486] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:21:29.487] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T14:21:49.194] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T14:21:49.195] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T15:15:36.250] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T15:15:36.254] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-17T15:15:42.544] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-17T15:15:42.545] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
